// <auto-generated />
using System;
using AnalyticsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnalyticsService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalyticsService.Data.ProductSalesSummary", b =>
                {
                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("Revenue")
                        .HasColumnType("bigint");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("integer");

                    b.HasKey("ShopId", "ProductId", "Date");

                    b.HasIndex("ShopId", "Date");

                    b.ToTable("ProductSalesSummaries");
                });

            modelBuilder.Entity("AnalyticsService.Data.SalesSummary", b =>
                {
                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<long>("Revenue")
                        .HasColumnType("bigint");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("integer");

                    b.HasKey("ShopId", "Date");

                    b.HasIndex("ShopId");

                    b.ToTable("SalesSummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
