// <auto-generated />
using System;
using AdService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdService.Data.AdCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<long>("BudgetCents")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<long>("SpentCents")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("Status");

                    b.ToTable("AdCampaigns");
                });

            modelBuilder.Entity("AdService.Data.CampaignMetrics", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<long>("Clicks")
                        .HasColumnType("bigint");

                    b.Property<long>("Conversions")
                        .HasColumnType("bigint");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CampaignId");

                    b.ToTable("CampaignMetrics");
                });

            modelBuilder.Entity("AdService.Data.CampaignProduct", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("CampaignId", "ProductId");

                    b.ToTable("CampaignProducts");
                });

            modelBuilder.Entity("AdService.Data.CampaignMetrics", b =>
                {
                    b.HasOne("AdService.Data.AdCampaign", "Campaign")
                        .WithOne("Metrics")
                        .HasForeignKey("AdService.Data.CampaignMetrics", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("AdService.Data.CampaignProduct", b =>
                {
                    b.HasOne("AdService.Data.AdCampaign", "Campaign")
                        .WithMany("Products")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("AdService.Data.AdCampaign", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
